CC = gcc
CFLAGS = -Wall -g -l pthread

PROGRAMS = deadlock deadlock-bug-exibicao \
           sem_central limite_lugares assimetrica \
	   tanen-sem tanen-4-2 tanen-5-1 

all: $(PROGRAMS)

clean:
	rm -f *.o *~ $(PROGRAMS)
