CC = gcc
CFLAGS = -Wall -g 
LDFLAGS = -l pthread

PROGRAMS = barreira1 barreira2 barreira2b \
	barreira3 barreira4 barreira5 \
	barreira_futex barrier_wait

all: $(PROGRAMS)

clean:
	rm -f *.o *~ $(PROGRAMS)
